steps:
  # Build the image using the project ID variable
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA', 
      '.'
    ]

  # Push the image to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']

options:
  # This line solved the "Failed to trigger build" error
  logging: CLOUD_LOGGING_ONLY
